# Generated by Django 4.0.5 on 2022-06-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='descripcion',
            new_name='Descripcion',
        ),
    ]
