# Generated by Django 4.0.5 on 2022-06-24 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_rename_descripcion_categoria_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('categoria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BlogApp.categoria')),
                ('Titulo', models.CharField(max_length=60)),
                ('Texto', models.CharField(max_length=500)),
            ],
            bases=('BlogApp.categoria',),
        ),
    ]
