# Generated by Django 4.0.5 on 2022-06-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Pais', models.CharField(max_length=30)),
                ('Edad', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='Nombre',
            new_name='Rubro',
        ),
    ]
