# Generated by Django 4.0.5 on 2022-06-24 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_usuario_rename_nombre_categoria_rubro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categorias',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='categoria_ptr',
            new_name='categorias_ptr',
        ),
    ]
